issue #819: Missing type for SPARQL repo config
Constructors that take SPARQL query and/or update endpoints did not set the type field properly. Repository managers could not retrieve the config information from the system repository without the type statement later, causing getRepository to fail with an exception:

org.eclipse.rdf4j.repository.config.RepositoryConfigException: Repository implementation for repository missing

Signed-off-by: Xiaofeng Li <luke.the.coder@gmail.com>