Keep BOM updated so they are valid dependencies
e.g. specify <type>war</type> were needed, remove
now missing rdf4j-sail-lucene4 etc.

Reordered a couple of dependencies so it is easier
to check against file system.

This avoids problems with maven site plugin when using the BOM,
which would otherwise log various errors from the dependency plugin,
e.g.

```
[WARNING] Unable to create Maven project for
org.eclipse.rdf4j:rdf4j-sail-lucene-test:pom:2.1.1 from repository.
org.apache.maven.project.ProjectBuildingException: Error resolving
project artifact: Failure to find
org.eclipse.rdf4j:rdf4j-sail-lucene-test:pom:2.1.1 in
https://repo.maven.apache.org/maven2 was cached in the local repository,
resolution will not be reattempted until the update interval of central
has elapsed or updates are forced for project
org.eclipse.rdf4j:rdf4j-sail-lucene-test:pom:2.1.1

```

Signed-off-by: Stian Soiland-Reyes <stain@apache.org>